version: "3.7"
services:
  backend:
    container_name: minecraft-skins
    build:
      context: .
    ports:
      - "${EXTERNAL_PORT}:4000"
    init: true
    env_file:
      .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 5m
      timeout: 10s
      retries: 2
      start_period: 10s
